#############################################################################
# Makefile for building: exnote
# Generated by qmake (2.01a) (Qt 4.7.4) on: Tue May 22 12:51:50 2012
# Project:  texteditor.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile texteditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DM_APPLICATION_NAME=\"${QMAKE_TARGET}\" -DM_APPLICATION_NAME=\"${QMAKE_TARGET}\" -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/linux-g++-maemo -I. -I/targets/HARMATTAN_X86/usr/include/qt4/QtCore -I/targets/HARMATTAN_X86/usr/include/qt4/QtGui -I/targets/HARMATTAN_X86/usr/include/qt4/QtDBus -I/targets/HARMATTAN_X86/usr/include/qt4 -I/targets/HARMATTAN_X86/usr/include/meegotouch -I/targets/HARMATTAN_X86/usr/include/meegotouch -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/lib -pie -rdynamic -lmeegotouchcore -lmeegotouchsettings -lmeegotouchextensions -lQtDBus -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainpage.cpp \
		filemodel.cpp \
		cell.cpp \
		editorpage.cpp \
		mlistitemcreator.cpp \
		aboutdialog.cpp \
		confirmdeletedialog.cpp moc_mainpage.cpp \
		moc_filemodel.cpp \
		moc_cell.cpp \
		moc_editorpage.cpp \
		moc_aboutdialog.cpp \
		moc_confirmdeletedialog.cpp
OBJECTS       = main.o \
		mainpage.o \
		filemodel.o \
		cell.o \
		editorpage.o \
		mlistitemcreator.o \
		aboutdialog.o \
		confirmdeletedialog.o \
		moc_mainpage.o \
		moc_filemodel.o \
		moc_cell.o \
		moc_editorpage.o \
		moc_aboutdialog.o \
		moc_confirmdeletedialog.o
DIST          = /targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/debug.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_defines.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_common.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch-boostable.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		texteditor.pro
QMAKE_TARGET  = exnote
DESTDIR       = 
TARGET        = exnote

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: texteditor.pro  /targets/HARMATTAN_X86/usr/share/qt4/mkspecs/linux-g++-maemo/qmake.conf /targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/debug.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_defines.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_common.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch-boostable.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile texteditor.pro
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/g++.conf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/unix.conf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/common/linux.conf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/qconfig.pri:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/default_pre.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/debug.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_defines.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch_common.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch-boostable.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/meegotouch.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/qt.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/moc.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/resources.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/uic.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/lex.prf:
/targets/HARMATTAN_X86/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile texteditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/exnote1.0.0 || $(MKDIR) .tmp/exnote1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/exnote1.0.0/ && $(COPY_FILE) --parents mainpage.h mainpage.h filemodel.h cell.h editorpage.h viewHeader.h mlistitemcreator.h aboutdialog.h confirmdeletedialog.h .tmp/exnote1.0.0/ && $(COPY_FILE) --parents main.cpp mainpage.cpp filemodel.cpp cell.cpp editorpage.cpp mlistitemcreator.cpp aboutdialog.cpp confirmdeletedialog.cpp .tmp/exnote1.0.0/ && (cd `dirname .tmp/exnote1.0.0` && $(TAR) exnote1.0.0.tar exnote1.0.0 && $(COMPRESS) exnote1.0.0.tar) && $(MOVE) `dirname .tmp/exnote1.0.0`/exnote1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/exnote1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_mgenerator_model_make_all:
compiler_mgenerator_model_clean:
	-$(DEL_FILE) ./gen_*
compiler_mgenerator_style_make_all:
compiler_mgenerator_style_clean:
	-$(DEL_FILE) ./gen_*
compiler_moc_header_make_all: moc_mainpage.cpp moc_mainpage.cpp moc_filemodel.cpp moc_cell.cpp moc_editorpage.cpp moc_aboutdialog.cpp moc_confirmdeletedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainpage.cpp moc_mainpage.cpp moc_filemodel.cpp moc_cell.cpp moc_editorpage.cpp moc_aboutdialog.cpp moc_confirmdeletedialog.cpp
moc_mainpage.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MApplicationPage \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpagemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mescapebuttonpanelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MDialog \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/maction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetaction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBanner \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbanner.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbannermodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MList \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlist.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractcellcreator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetRecycler \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetrecycler.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MObjectMenu \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenu.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenumodel.h \
		filemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractItemModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MExport \
		mainpage.h
	mmoc $(DEFINES) $(INCPATH) mainpage.h -o moc_mainpage.cpp

moc_mainpage.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MApplicationPage \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpagemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mescapebuttonpanelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MDialog \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/maction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetaction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBanner \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbanner.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbannermodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MList \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlist.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractcellcreator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetRecycler \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetrecycler.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MObjectMenu \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenu.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenumodel.h \
		filemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractItemModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MExport \
		mainpage.h
	mmoc $(DEFINES) $(INCPATH) mainpage.h -o moc_mainpage.cpp

moc_filemodel.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractItemModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MExport \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		filemodel.h
	mmoc $(DEFINES) $(INCPATH) filemodel.h -o moc_filemodel.cpp

moc_cell.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MListItem \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitem.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetController \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetModel \
		cell.h
	mmoc $(DEFINES) $(INCPATH) cell.h -o moc_cell.cpp

moc_editorpage.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MSheet \
		/targets/HARMATTAN_X86/usr/include/meegotouch/msheet.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/msheetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MRichTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mrichtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtexteditmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBasicSheetHeader \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasicsheetheader.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasicsheetheadermodel.h \
		editorpage.h
	mmoc $(DEFINES) $(INCPATH) editorpage.h -o moc_editorpage.cpp

moc_aboutdialog.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MDialog \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		aboutdialog.h
	mmoc $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_confirmdeletedialog.cpp: /targets/HARMATTAN_X86/usr/include/meegotouch/MMessageBox \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mmessagebox.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mmessageboxmodel.h \
		confirmdeletedialog.h
	mmoc $(DEFINES) $(INCPATH) confirmdeletedialog.h -o moc_confirmdeletedialog.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp /targets/HARMATTAN_X86/usr/include/meegotouch/MApplication \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplication.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MApplicationWindow \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MApplicationPage \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpagemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mescapebuttonpanelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MButton \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbutton.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbuttonmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MToolBar \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtoolbar.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/maction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetaction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtexteditmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MExport \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MComponentCache \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mcomponentcache.h \
		mainpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MDialog \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBanner \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbanner.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbannermodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MList \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlist.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractcellcreator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetRecycler \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetrecycler.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MObjectMenu \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenu.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenumodel.h \
		filemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractItemModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractitemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainpage.o: mainpage.cpp /targets/HARMATTAN_X86/usr/include/meegotouch/MLinearLayoutPolicy \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlinearlayoutpolicy.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractlayoutpolicy.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MButton \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbutton.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbuttonmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLayout \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlayout.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MToolBar \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtoolbar.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/maction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtexteditmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MSceneWindow \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MApplication \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplication.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MOnDisplayChangeEvent \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mondisplaychangeevent.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MApplicationWindow \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MTheme \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MGridLayoutPolicy \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mgridlayoutpolicy.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MImageWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mimagewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mimagewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MPannableViewport \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannableviewport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannableviewportmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MSeparator \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mseparator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetController \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mseparatormodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MMessageBox \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mmessagebox.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mmessageboxmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractCellCreator \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractcellcreator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetRecycler \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetrecycler.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MList \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlist.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBasicListItem \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasiclistitem.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitem.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MSceneManager \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenemanager.h \
		mainpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MApplicationPage \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mapplicationpagemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mescapebuttonpanelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MDialog \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetaction.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBanner \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbanner.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbannermodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MObjectMenu \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenu.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mobjectmenumodel.h \
		filemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractItemModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MExport \
		viewHeader.h \
		editorpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MSheet \
		/targets/HARMATTAN_X86/usr/include/meegotouch/msheet.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/msheetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MRichTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mrichtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBasicSheetHeader \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasicsheetheader.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasicsheetheadermodel.h \
		mlistitemcreator.h \
		aboutdialog.h \
		confirmdeletedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainpage.o mainpage.cpp

filemodel.o: filemodel.cpp filemodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractItemModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MExport \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filemodel.o filemodel.cpp

cell.o: cell.cpp /targets/HARMATTAN_X86/usr/include/meegotouch/MLayout \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlayout.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLinearLayoutPolicy \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlinearlayoutpolicy.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractlayoutpolicy.h \
		cell.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MListItem \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitem.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetController \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetModel
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o cell.cpp

editorpage.o: editorpage.cpp /targets/HARMATTAN_X86/usr/include/meegotouch/MLayout \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlayout.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MPannableViewport \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannableviewport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannableviewportmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLinearLayoutPolicy \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlinearlayoutpolicy.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractlayoutpolicy.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MRichTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mrichtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MTextEdit \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtextedit.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtexteditmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAction \
		/targets/HARMATTAN_X86/usr/include/meegotouch/maction.h \
		editorpage.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MSheet \
		/targets/HARMATTAN_X86/usr/include/meegotouch/msheet.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/msheetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBasicSheetHeader \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasicsheetheader.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasicsheetheadermodel.h \
		viewHeader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorpage.o editorpage.cpp

mlistitemcreator.o: mlistitemcreator.cpp mlistitemcreator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MAbstractCellCreator \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mabstractcellcreator.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetRecycler \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetrecycler.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MBasicListItem \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbasiclistitem.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitem.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetController \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlistitemmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MWidgetModel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mlistitemcreator.o mlistitemcreator.cpp

aboutdialog.o: aboutdialog.cpp /targets/HARMATTAN_X86/usr/include/meegotouch/MLabel \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mlabelmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MImageWidget \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mimagewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mimagewidgetmodel.h \
		aboutdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MDialog \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

confirmdeletedialog.o: confirmdeletedialog.cpp /targets/HARMATTAN_X86/usr/include/meegotouch/MButton \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbutton.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetcontroller.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mexport.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mnamespace.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mtheme.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mbuttonmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mwidgetmodel.h \
		confirmdeletedialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/MMessageBox \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mmessagebox.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialog.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindow.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mscenewindowmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mdialogmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidget.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mphysics2dpanning.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mpannablewidgetmodel.h \
		/targets/HARMATTAN_X86/usr/include/meegotouch/mmessageboxmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confirmdeletedialog.o confirmdeletedialog.cpp

moc_mainpage.o: moc_mainpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainpage.o moc_mainpage.cpp

moc_filemodel.o: moc_filemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filemodel.o moc_filemodel.cpp

moc_cell.o: moc_cell.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cell.o moc_cell.cpp

moc_editorpage.o: moc_editorpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorpage.o moc_editorpage.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_confirmdeletedialog.o: moc_confirmdeletedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_confirmdeletedialog.o moc_confirmdeletedialog.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/exnote/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/exnote/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/exnote/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/exnote/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/exnote/bin/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) /home/Tomek/texteditor/data/exnote.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/exnote.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/Tomek/texteditor/data/exnote.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/exnote.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_css: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/exnote/style/ || $(MKDIR) $(INSTALL_ROOT)/opt/exnote/style/ 
	-$(INSTALL_FILE) /home/Tomek/texteditor/data/exnote.css $(INSTALL_ROOT)/opt/exnote/style/


uninstall_css:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/exnote/style/exnote.css
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/exnote/style/ 


install_gfx: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/exnote/data/ || $(MKDIR) $(INSTALL_ROOT)/opt/exnote/data/ 
	-$(INSTALL_FILE) /home/Tomek/texteditor/data/dialog-question.png $(INSTALL_ROOT)/opt/exnote/data/


uninstall_gfx:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/exnote/data/dialog-question.png
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/exnote/data/ 


install:  install_target install_icon install_desktop install_css install_gfx  FORCE

uninstall: uninstall_target uninstall_icon uninstall_desktop uninstall_css uninstall_gfx   FORCE

FORCE:

